name: Calcmod Updater
description:
  A GitHub Action to update the gradle.properties file with the latest stable
  version of Minecraft and Fabric API.
author: js802025

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github-token:
    description: GitHub token
    required: true

# Define your outputs here.
outputs:

runs:
  using: node24
  main: dist/index.js
